/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EnterpriseSelector: typeof import('./src/components/EnterpriseSelector.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TotpForm: typeof import('./src/components/TotpForm.vue')['default']
  }
}
